### PR TITLE
Design icons

### PR DESCRIPTION
**Pull request by amir167**
changed the design of icons in the same style

Screen

### CODE REVIEW

**Comment by AbdullahAlfaraj** [comment]
Thank you for your contribution. I've merged it in #308 
when you get the time do you think you can do one for reactivating the last selection area button?

image

**Comment by amir167** [comment]
I will do it soon

**Comment by amir167** [comment]
svg
selection-area_2

**Comment by amir167** [comment]
+ new commit for writing-icon.svg
background-size: 25px;

before

Снимок экрана 2023-07-01 213506

new

**Comment by amir167** [comment]
new commit for search.svg

background-image: url(./icon/search.svg);
background-size: 30px;

before


after

**Pull request merged**
