### PR TITLE
fix: update adetailer options

### PR DESCRIPTION
**Pull request by Bing-su**
fixes: #334 

In June, I made breaking changes and also renamed the script.

This change brings it up to date, but it also will cause issues with adetailer versions, so please merge carefully.

### CODE REVIEW

**Comment by AbdullahAlfaraj** [comment]
@Bing-su, Thank you for developing the ADetailer and for submitting this PR too. will merge it soon!

**Comment by XiaoCC** [comment]
我本地拉取了这个代码重新编译后  还是无法使用该插件

**Comment by XiaoCC** [comment]
image
image
ADetailer   ultimate sd upscale   无法使用    one button prompt 下拉列表为空    sd版本1.5.1

**Comment by AbdullahAlfaraj** [comment]
> 我本地拉取了这个代码重新编译后 还是无法使用该插件

@XiaoCC, you could try pulling from the commit with the hash https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/commit/fd134ef7b261e1fa4897d2725593f9d93303cd4f. Let me know if that works for you.

**Pull request merged**
