### PR TITLE
Update duckduckgo_search to v3.9.6

### PR DESCRIPTION
**Pull request by deedy5**
update duckduckgo_search to v3.9.6

### CODE REVIEW

**Comment by AbdullahAlfaraj** [comment]
Thank you! I've went ahead and incremented to the latest release v3.9.9

**Comment by deedy5** [comment]
Hi.
There is also a problem with versions in requirements.txt, ddgs gives errors.
I haven't looked into it in detail, but at least set httpcore==1.0.2

**Comment by AbdullahAlfaraj** [comment]
Ah, that might be why I bumped into this error when I was trying to get this PR merged. 

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13840

Looks like ddgs versions 3.9.5 and up could be causing the same error because they depend on httpx 0.25.1 or later, which brings in httpcore v1.0.2. But, I’ve rolled back httpx to 0.24.1 and now both automatic1111 and ddgs are back in action. 
https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/blob/4d8ccde513ba2d951b766e72eff4352949d9a437/install.py#L74

image

**Comment by deedy5** [comment]
I'll revisit the `python_server` folder later and update the code and all packages to the latest versions.

**Pull request merged**
