### PR TITLE
add support to 'After Detailer' always on script

### PR DESCRIPTION
**Pull request by AbdullahAlfaraj**

### CODE REVIEW

**Comment by xueqing0622** [comment]
no see After Detailer in script, how to active it.

**Comment by AbdullahAlfaraj** [comment]
@xueqing0622 It's available in v1.2.6

**Comment by xueqing0622** [comment]
Thanks! "LoRA Block Weight" also work in "auto-photoshop-sd"
how about add "Dynamic Thresholding (CFG Scale Fix)"  "Regional Prompter" "LLuL - Local Latent upscaLer" in "auto-photoshop-sd"
have a nice day

**Comment by AbdullahAlfaraj** [comment]
@xueqing0622 Yes open an issue for each of the suggestions, and we could discuss them separately there.

**Pull request merged**
